# Generated by Django 4.2.5 on 2023-09-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='person',
            name='calorie',
        ),
    ]
