# Generated by Django 4.2.5 on 2023-09-30 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_remove_person_bmi_remove_person_calorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodrestriction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='foodrestriction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='foodrestriction',
            name='family',
        ),
        migrations.RemoveField(
            model_name='foodrestriction',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='foodrestriction',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='foodrestriction',
            name='food_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_backend.foodcategory'),
        ),
    ]
