# Generated by Django 4.2.5 on 2023-09-30 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0003_remove_foodrestriction_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_backend.foodcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='food_categories',
            field=models.ManyToManyField(through='app_backend.ProductCategory', to='app_backend.foodcategory'),
        ),
    ]
