# Generated by Django 4.2.5 on 2023-09-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_productcategory_product_food_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodrestriction',
            unique_together={('person', 'food_category')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'food_category')},
        ),
    ]
