# Generated by Django 4.2.5 on 2023-09-30 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_alter_foodrestriction_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app_backend.family'),
        ),
        migrations.AlterField(
            model_name='person',
            name='food_restrictions',
            field=models.ManyToManyField(related_name='persons', through='app_backend.FoodRestriction', to='app_backend.foodcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='food_categories',
            field=models.ManyToManyField(related_name='products', through='app_backend.ProductCategory', to='app_backend.foodcategory'),
        ),
    ]
