# Generated by Django 4.2.5 on 2023-10-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_alter_person_family_alter_person_food_restrictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='activity_level',
            field=models.IntegerField(choices=[(1, 'Sedentary'), (2, 'Lightly Active'), (3, 'Moderately Active'), (4, 'Very Active'), (5, 'Extra Active')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')]),
        ),
    ]
