# Generated by Django 4.2.5 on 2023-10-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0008_alter_person_first_name_alter_person_last_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodrestriction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='person',
            name='food_restrictions',
        ),
        migrations.AddField(
            model_name='family',
            name='food_restrictions',
            field=models.ManyToManyField(related_name='families', through='app_backend.FoodRestriction', to='app_backend.foodcategory'),
        ),
        migrations.AddField(
            model_name='foodrestriction',
            name='family',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_backend.family'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='foodrestriction',
            unique_together={('family', 'food_category')},
        ),
        migrations.RemoveField(
            model_name='foodrestriction',
            name='person',
        ),
    ]
