# Generated by Django 4.2.5 on 2023-10-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_alter_foodrestriction_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_qty',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField()),
                ('modified_by', models.UUIDField()),
                ('serving_size', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('carbohydrate_calorie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein_calorie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fat_calorie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateField()),
                ('batch_no', models.CharField(max_length=50)),
                ('total_qty', models.IntegerField(default=1)),
                ('available_qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='app_backend.product')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='app_backend.storage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
