# Generated by Django 4.2.5 on 2023-12-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0010_remove_product_available_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='carbohydrate_calorie',
            new_name='calorie',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fat_calorie',
            new_name='carbohydrate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='protein_calorie',
            new_name='cholesterol',
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sodium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
