# Generated by Django 4.2.5 on 2024-02-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0010_remove_product_available_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ngo_manager',
            field=models.BooleanField(default=False),
        ),
    ]
