# Generated by Django 4.2.5 on 2024-02-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0011_user_is_ngo_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.UUIDField(default='cf2ccad0a6b445f087d50a3ef9c48e6f'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_by',
            field=models.UUIDField(default='cf2ccad0a6b445f087d50a3ef9c48e6f'),
        ),
    ]
