# Generated by Django 4.2.5 on 2024-02-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0012_user_created_by_user_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_by',
            field=models.UUIDField(),
        ),
    ]
