# Generated by Django 4.2.5 on 2024-02-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0014_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')]),
        ),
    ]
