# Generated by Django 4.2.5 on 2024-03-01 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0016_remove_product_carbohydrate_calorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='created_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='family',
            name='modified_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='created_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='modified_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='modified_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='storage',
            name='created_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='storage',
            name='modified_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_by',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
    ]
