# Generated by Django 4.2.5 on 2024-03-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0017_alter_family_created_by_alter_family_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
