# Generated by Django 4.2.5 on 2024-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0018_alter_user_profile_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
