# Generated by Django 4.2.5 on 2024-03-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0021_alter_user_created_by_alter_user_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='x',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='y',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='z',
        ),
    ]
