# Generated by Django 4.2.5 on 2024-03-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0024_allocation_allocationfamily_allocationinventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='min_product_category',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ONGOING', 'Ongoing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='CREATED', max_length=20),
        ),
    ]
