# Generated by Django 4.2.5 on 2024-03-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0025_alter_allocation_min_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='min_product_category',
        ),
        migrations.AddField(
            model_name='allocation',
            name='allocation_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='allocationinventory',
            name='max_quantity_per_family',
            field=models.IntegerField(default=0),
        ),
    ]
