# Generated by Django 4.2.5 on 2024-03-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0026_remove_allocation_min_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationfamily',
            name='calorie_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='calorie_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='carbohydrate_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='carbohydrate_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='cholesterol_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='cholesterol_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='fat_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='fat_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='fiber_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='fiber_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='protein_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='protein_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='saturated_fat_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='saturated_fat_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='sodium_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='sodium_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='status',
            field=models.CharField(choices=[('SERVED', 'Served'), ('NOT_SERVED', 'Not Served'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='sugar_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='allocationfamily',
            name='sugar_needed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
