# Generated by Django 4.2.5 on 2024-03-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0027_allocationfamily_calorie_allocated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='diversification',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ONGOING', 'Ongoing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='allocationfamily',
            name='status',
            field=models.CharField(choices=[('SERVED', 'Served'), ('NOT_SERVED', 'Not Served'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
