# Generated by Django 4.2.5 on 2024-03-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0028_allocation_diversification_alter_allocation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
