# Generated by Django 4.2.5 on 2024-03-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0029_alter_product_product_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
