# Generated by Django 5.0.3 on 2024-03-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0032_package_allocation_alter_package_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehistory',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
