# Generated by Django 5.0.3 on 2024-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0033_packagehistory_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationfamily',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('NOT_SERVED', 'Not Served'), ('SERVED', 'Served'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
