# Generated by Django 5.0.3 on 2024-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0035_nutritionallabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionallabel',
            name='image',
            field=models.ImageField(unique=True, upload_to='nutritional_label/'),
        ),
    ]
